// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231030014949_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Entidades.Persona", b =>
                {
                    b.Property<int>("NInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("N_INTERNO");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("APELLIDOS");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ADMIN");

                    b.Property<decimal?>("NInternoResp")
                        .HasColumnType("numeric")
                        .HasColumnName("N_INTERNO_RESP");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("NOMBRE");

                    b.Property<string>("UsuarioRed")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("USUARIO_RED");

                    b.HasKey("NInterno");

                    b.ToTable("Personal");
                });
#pragma warning restore 612, 618
        }
    }
}
